### ISSUE TITLE
Add IfInvalidThenValidate Functionallity

### ISSUE THREAD

**Issue by svzieg** [peasy/peasy-js#31]
Hey, 

Currently I have the case, I need to build some "OR" Functionality. 
So I have two conditions, lets say: 

PersonIsYoungEnoughRule => person.age < 27    and the rule
PersonIsStudent => person.job === student. 

Now I want to build a rule by concatenating the conditions by an OR. So the command would check a rule like:

PersonIsYoungEnoughOrStudentRule = PersonIsYoungEnoughRule.ifInvalidthenValidate(PersonIsStudent)

Of course I could create that rule manuell or performing two Checks, but I also need that functionality in deeply interleaved rules. Such as:

If ((A and (B or C)) or (D and A) or (B and C)) ... then ...

which makes the conversions process a bit more tricky. 
Therefore it would be nice if Peasy-JS, which already handles the AND-Connectors by the 'ifValidThenValidate' functionality, could also handle that case.

Best Regards 
Sven

**Comment by ahanusa** [comment]
Very interesting use case.  A very quick “hack” would be to just create one rule that has both of your OR conditions in it, and name it accordingly “PersonVerificationRule”.

Let me think about this some more.  

Do you have any thoughts how this might look from an API perspective?

I’m accepting contributions too, so feel free to submit a pull request if you come up with something!

**Comment by ahanusa** [comment]
Another, “less hacky” way to do it would be to create a rule that consumes your PersonIsYoungEnough and PersonIsStudent rules and validate the rule based on the outcome of those rules.

You could think of it as an orchestration rule.

**Comment by svzieg** [comment]
ok your Idea of creating a rule which consumes other rules sounds interesting. I will keep that in mind. 

But, after having a quick look to the source code, I think it could also be implemented in peasy-js quite easily, since you already have a similar functionality for the `ifValidThenValidate` - Case. The Idea could be, to use that functionality to create a `ifInvalidThenValidate` Function, which takes either one rule or an array of rules, like the `ifValidThenValidate`-Function. 

The Semantic behind the evaluation would then be: 
* the rule is invalid if the rule and ONE of the InvalidSuccessors is invalid
* the rule is valid if the rule OR ALL InvalidSuccessors are valid.

With that you can easily create AND and OR connectors. Logical-AND is used by default (or by using ifValidThenValidate) and logical-OR can be used by chaining rules with `ifInvalidThenValidate`, since `A.ifInvalidThenValidate(B)` is invalid if A AND B is invalid, and valid if A is valid OR B is valid OR (A AND B) is valid as long as nobody writes something like: 
```
A.ifInvalidThenValidate(B); 
A.ifValidThenValidate(B);
```
But in this case the A rule seems to be useless to me.  

Tomorrow I will have a deeper look into the source code. After I can say more.

**Comment by svzieg** [comment]
Hey ahanusa , 

I just forked the project and implemented the missing functionality. 
Since I haven't written any tests for it in jasmine, but tested it in my project I do not start a pull request yet. I will implement some jasmine tests later. All actual implemented jasmine-tests passed. 

Feel free to have a look at it, if your free.

**Comment by ahanusa** [comment]
Looks good, if you add test coverage for your changes, I'll merge it in!  Let me know if you need assistance with that.

Thanks for your contribution, we appreciate it!

**Comment by ahanusa** [comment]
Nice work, thanks again!
